export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  TABLES = '/tables',
  PENDING = '/pending',
  CANCELLED = '/cancelled',
  DELIVERED = '/delivered',
  STRIPE_PAYMENT = '/stripe_payment',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  SUPLIER_HOME = '/supplier_home',
  GARAGEUSER_HOME = '/user_home_page',
  USER_HOME = '/user_home',
  USER_REVIEW_PAGE = '/user_review_page',
  GARAGE_PROFILE = '/garage_profile',
  GARAGE_REVIEW_PAGE = '/garage_review_page',
  MANAGE_USER_REQUESTS = '/manage_requests',
  ALL_GARAGES = '/all_garages',
  GARAGE_HOME = '/garage_home',
  GARAGE_ACTIVE_SERVICES = '/garage_active_services',
  CONTACT = '/contact',
  TABLES_PENDING = '/tables/pending',
  LOGIN = '/login'
}
